# Prometheus configuration for Cards API monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cards-api-local'
    environment: 'development'

# Alert rules
rule_files:
  - 'prometheus_alerts.yml'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Scrape configurations
scrape_configs:
  # Cards API metrics
  - job_name: 'cards-api'
    static_configs:
      - targets: ['cards-api:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (if pg_exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

